// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n=Integer.parseInt(args[0]);
		double above=0;
		double below=0;
		double rnd;
		double ratio;
		for (int i = 0; i < n; i++)
		{
			rnd=Math.random();
			if (rnd>0.5) {
				above++;
			}
			else
			{
				below++;
			}

		}
		if (above==0 | below==0) {
			System.out.println("> 0.5: "+(int)above+" times");
			System.out.println("<= 0.5: "+(int)below+" times");
		}
		else
		{
			ratio=above/below;
			System.out.println("> 0.5: "+(int)above+" times");
			System.out.println("<= 0.5: "+(int)below+" times");
			System.out.println("Ratio: "+ratio);
		}			
	}
}
